### ISSUE TITLE
LilyPi ILI9481 (GT911) not working

### ISSUE THREAD

**Issue by Juno63** [Xinyuan-LilyGO/LilyPi#1]
I am trying to get a LilyPi ILI9481 (GT911) working with the latest TTGO_TWatch_Library V1.4.2, but just uncommenting the #define LILYGO_BLOCK_ILI9481_MODULE (and commenting #define LILYGO_BLOCK_ST7796S_MODULE) doesn't seem enough to make the lv-demo_widgets example work. Exactly what do I have to change more?

**Comment by LilyGO** [comment]
Hello, is burning using firmware working properly? https://github.com/Xinyuan-LilyGO/LilyPi/tree/main/firmware

**Comment by Juno63** [comment]
No, Burning firmware [LILYPI_ILI9481(K113-01)_20200930.bin] (https://github.com/Xinyuan-LilyGO/LilyPi/blob/main/firmware/LILYPI_ILI9481(K113-01)_20200930.bin) succeeded, but black screen.

**Comment by LilyGO** [comment]
What does the serial port print? Did you buy the IL9481 version?

**Comment by Juno63** [comment]
Yes, I bought the ILI9481 version. Now I succeedded 9after rebooting) to restore the firmware, which is working again.
But...this is a binary file. If we cannot read the code or reconstruct the code, we cannot use LilyPi with LVGL, like shown in lv-demo_widgets.
Please help to make the example work for ILI9481 (GT911) version.

**Comment by Juno63** [comment]
Maybe the board is not defined well?
File: boards/lilypi_v1.h
#define TFT_WIDTH                   240  	// must be 480 
#define TFT_HEIGHT                  240		//must be 320
#define SD_CS               13			//must be 15
#define SD_MISO             2
#define SD_MOSI             15			//must be 13
#define SD_SCLK             14
#define TOUCH_INT           39			// must be 34
#define RTC_INT_PIN             36

**Comment by Juno63** [comment]
An Touch_Driver for GTXX is not defined yet?
File: TTGO.h
#if     defined(LILYGO_TOUCH_DRIVER_GTXXX)
        //TODO:

**Comment by Juno63** [comment]
Or:
File: TFT_eSPI.h
#define ILI9481_DRIVER
// ST7796 is compatible with ST7789 instructions
// #include "TFT_Drivers/ST7789_Defines.h"

Here "TFT_Drivers/ILI9481_Defines.h" is not included. (?)

**Comment by LilyGO** [comment]
In the config. h .  Uncomment the macro definition    LILYGO_BLOCK_ILI9481_MODULE
![1](https://user-images.githubusercontent.com/31160602/158546842-b3cd8948-6824-448b-9ff9-b33d84145ebe.png)

**Comment by Juno63** [comment]
I did, see my starting question. This is not sufficient, it doesn't work.

**Comment by LilyGO** [comment]
TFT_eSPI librar
![1](https://user-images.githubusercontent.com/31160602/158759470-44572151-7d9b-4f01-9bf8-a432db36f90f.png)
y

**Comment by Juno63** [comment]
I read about this setting, but this file is not in your (examples) library.

**Comment by LilyGO** [comment]
Based on the library at https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library

**Comment by LilyGO** [comment]
Has the problem been solved? I will close this problem

**Comment by Juno63** [comment]
No, not solved. 
Touch_Driver for GTXX is not defined yet.
File: TTGO.h
#if defined(LILYGO_TOUCH_DRIVER_GTXXX)
//TODO:

**Comment by LilyGO** [comment]
Can you send screenshots of your compilation errors?
